version: "3.7"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nc-db

  nextcloud-db:
    image: mariadb:10.6
    container_name: nc-db
    hostname: nc-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=msqyld-bin --binlog-format=ROW
    environment:
      MYSQL_USER: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_ROOT_PASSWORD: 1123
      MYSQL_PASSWORD: 123

  samba:
    image: my/samba
    tty: true
    volumes:
      - ./samba:/Shared
    ports:
      - "139:139"
      - "445:445"


