version: '3'
services:

  bareos-dir:
    container_name: bareos-dir
    image: feelinglight/bareos-dir:23.0.3
    restart: unless-stopped
    networks:
      - homelab
    # command: sleep 10000000
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      # !! После изменений этих переменных не забыть закомментировать и
      # сделать повторный docker-compose up -d

      # Нужно только при первом запуске
      # - DB_INIT=true
      # Нужно только при обновлении bareos
      # - DB_UPDATE=true
      ###
      - BAREOS__DB_HOST=${POSTGRES_HOST}
      - BAREOS__DB_PORT=${POSTGRES_PORT}
      - BAREOS__DB_NAME=bareos
      - BAREOS__DB_USER=bareos
      - BAREOS__DB_PASSWORD=${BAREOS__DB_PASSWORD}

      - BAREOS__OUTER_ADDRESS=${BAREOS_DOMAIN}:9100
      ###
      - POSTGRES_ADMIN_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      ###
      - BAREOS__DIRECTOR_PASSWORD=${BAREOS__DIRECTOR_PASSWORD}
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}
      - BAREOS__WEBUI_CONSOLE_PASSWORD=${BAREOS__WEBUI_CONSOLE_PASSWORD}
      ###
      - BAREOS__SD_ADDRESS=bareos-sd
      - BAREOS__SD_PASSWORD=${BAREOS__SD_PASSWORD}
      ###
      - BAREOS__FD_DOCKER_ADDRESS=${BAREOS__FD_DOCKER_ADDRESS}
      - BAREOS__FD_DOCKER_PASSWORD=${BAREOS__FD_DOCKER_PASSWORD}

      - BAREOS__FD_DMITRY_ADDRESS=${BAREOS__FD_DMITRY_ADDRESS}
      - BAREOS__FD_DMITRY_PASSWORD=${BAREOS__FD_DMITRY_PASSWORD}

      - BAREOS__FD_TANYA_ADDRESS=${BAREOS__FD_TANYA_ADDRESS}
      - BAREOS__FD_TANYA_PASSWORD=${BAREOS__FD_TANYA_PASSWORD}

      - BAREOS__FD_TANYA_LINUX_ADDRESS=${BAREOS__FD_TANYA_LINUX_ADDRESS}
      - BAREOS__FD_TANYA_LINUX_PASSWORD=${BAREOS__FD_TANYA_LINUX_PASSWORD}

      - BAREOS__FD_HOMELAB_ADDRESS=${BAREOS__FD_HOMELAB_ADDRESS}
      - BAREOS__FD_HOMELAB_PASSWORD=${BAREOS__FD_HOMELAB_PASSWORD}
      ###
      - BAREOS__SMTP_ADDRESS=${BAREOS__SMTP_ADDRESS}
      - BAREOS__SMTP_PORT=${BAREOS__SMTP_PORT}
      - BAREOS__SMTP_LOGIN=${BAREOS__SMTP_LOGIN}
      - BAREOS__SMTP_PASSWORD=${BAREOS__SMTP_PASSWORD}
      - BAREOS__SMTP_FROM=${BAREOS__SMTP_FROM}
      - BAREOS__SMTP_TO=${BAREOS__SMTP_TO}
    ports:
      - 9101:9101
    volumes:
      - ./services/bareos/config/etc_bareos/dir:/etc_bareos:ro
      - ./services/bareos/config/scripts:/usr/local/bin/
      - ./services/bareos/logs:/var/log/bareos
      # Важно биндить, потому что если сделать обычный проброс, то докер автоматически создаст
      # папку и будет писать туда бэкапы.
      - type: bind
        source: /mnt/backups
        target: /backups

      # Для отладки
      # - ./services/bareos/docker/make_bareos_config.sh:/scripts/make_bareos_config.sh
      # - ./services/bareos/docker/director-entrypoint.sh:/scripts/director-entrypoint.sh
    depends_on:
      postgres-db:
        condition: service_healthy

  bareos-sd:
    container_name: bareos-sd
    image: feelinglight/bareos-sd:23.0.3
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - 9103:9103
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - BAREOS__SD_PASSWORD=${BAREOS__SD_PASSWORD}
      - BAREOS__SD_MONITOR_PASSWORD=${BAREOS__SD_MONITOR_PASSWORD}
    volumes:
      - ./services/bareos/config/etc_bareos/sd:/etc_bareos:ro
      - type: bind
        source: /mnt/backups
        target: /backups


  # bareos-fd:
  #   container_name: bareos-fd
  #   image: feelinglight/bareos-fd:23.0.3
  #   restart: unless-stopped
  #   networks:
  #     - homelab
  #   environment:
  #     - TZ=Asia/Yekaterinburg
  #     ###
  #     - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}
  #     - BAREOS__FD_DOCKER_PASSWORD=${BAREOS__FD_DOCKER_PASSWORD}
  #   volumes:
  #     - ./services/bareos/config/etc_bareos/fd:/etc_bareos:ro
  #     - ./services/bareos/data/docker-fd-data:/docker-fd-data

  bareos-webui:
    container_name: bareos-webui
    image: feelinglight/bareos-webui:23.0.3
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - BAREOS__DIRECTOR_HOST=bareos-dir
    volumes:
      - ./services/bareos/config/etc_bareos/webui:/etc_bareos:ro

  smtp-relay:
    container_name: smtp-relay
    image: juanluisbaptiste/postfix:1.7.1
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - SMTP_SERVER=${BAREOS__SMTP_ADDRESS}
      - SMTP_USERNAME=${BAREOS__SMTP_LOGIN}
      - SMTP_PASSWORD=${BAREOS__SMTP_PASSWORD}
      - SERVER_HOSTNAME=${BAREOS__SMTP_SENDER}

