version: '3'
services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      retries: 20
    volumes:
      - ./services/postgres/data/:/var/lib/postgresql/data
      - ./services/postgres/backup/:/backup

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    networks:
      - homelab
    user: ${SERVER_UID}:${SERVER_GID}
    environment:
      TZ: Asia/Yekaterinburg
      ###
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
    # If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    # https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    stop_grace_period: 5s
    # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command:
      - --innodb-buffer-pool-size=512M
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=512
      - --innodb-rollback-on-timeout=OFF
      - --innodb-lock-wait-timeout=120
    volumes:
      - ./services/mariadb/data:/var/lib/mysql
      - ./services/mariadb/backup/:/backup

  redis:
    image: redis:7.4.1
    container_name: redis
    restart: unless-stopped
    networks:
      - homelab
    user: ${SERVER_UID}:${SERVER_GID}
    environment:
      TZ: Asia/Yekaterinburg
    volumes:
      - ./services/redis/data:/data

