---
version: "3.4"

services:

  homer:
    image: b4bz/homer:v24.04.1
    container_name: homer
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
    networks:
      - homelab
    volumes:
      - ./services/homer/assets:/www/assets


  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"

      - REGRU_USERNAME=${REGRU_USERNAME}
      - REGRU_PASSWORD=${REGRU_PASSWORD}

      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - AUTHELIA_DOMAIN=${AUTHELIA_DOMAIN}
      - PIHOLE_DOMAIN=${PIHOLE_DOMAIN}
      - HOMER_DOMAIN=${HOMER_DOMAIN}
      - BAREOS_DOMAIN=${BAREOS_DOMAIN}
      - GLANCES_DOMAIN=${GLANCES_DOMAIN}
      - GITEA_DOMAIN=${GITEA_DOMAIN}

    networks:
      - homelab
    ports:
      - 80:80
      - 443:443
      - 2222:2222
    volumes:
      - ./services/traefik/config/:/etc/traefik:ro
      - ./services/traefik/logs:/var/log/traefik
      - ./services/traefik/data/acme:/letsencrypt


  authelia:
    image: authelia/authelia:4.38.8
    container_name: authelia
    restart: unless-stopped
    user: ${SERVER_USER_UID_GID}
    environment:
      - TZ='Asia/Yekaterinburg'

      - X_AUTHELIA_CONFIG_FILTERS=template
      - JWT_SECRET=${JWT_SECRET}
      - STORAGE_ENCRYPTION_KEY=${STORAGE_ENCRYPTION_KEY}

      - SERVICES_DOMAIN=${SERVICES_DOMAIN}
      - AUTHELIA_DOMAIN=${AUTHELIA_DOMAIN}
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
      - PIHOLE_DOMAIN=${PIHOLE_DOMAIN}
      - HOMER_DOMAIN=${HOMER_DOMAIN}
      - BAREOS_DOMAIN=${BAREOS_DOMAIN}
      - GLANCES_DOMAIN=${GLANCES_DOMAIN}
      - GITEA_DOMAIN=${GITEA_DOMAIN}
    networks:
      - homelab
    volumes:
      - ./services/authelia/config:/config


  pihole:
    image: pihole/pihole:2024.03.2
    container_name: pihole
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ='Asia/Yekaterinburg'

      - VIRTUAL_HOST=${PIHOLE_DOMAIN}
      - FTLCONF_LOCAL_IPV4=${SERVER_IP}
    volumes:
      - ./services/pihole/config/etc-pihole:/etc/pihole
      - ./services/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./services/pihole/backup:/backup

...

