---
- hosts: home_server
  vars:
    - server_data_dir: "/home_server"
    - sites:
      - {"name": "s1", "path": "~/develop/hugo/multisite/sites/s1/public", "domain": "s1.home"}
      - {"name": "s2", "path": "~/develop/hugo/multisite/sites/s2/public", "domain": "s2.home"}
  tasks:
    - include_role:
        name: site
      vars:
        site_info: "{{ item }}"
      with_items:
        - "{{ sites }}"
  #roles:
    #- http_server
    #- git_server
