---
version: "3.4"

services:

  glances:
    image: nicolargo/glances:dev
    container_name: glances
    restart: unless-stopped
    network_mode: "host"
    pid: host
    privileged: true
    environment:
      - TZ="Asia/Yekaterinburg"
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/glances/glances.conf:/glances/conf/glances.conf"
      - /:/rootfs:ro


  gitea:
    image: gitea/gitea:1.22.1
    container_name: gitea
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ="Asia/Yekaterinburg"
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8

      # Нужно для разрешения записи в /home/git/.ssh
      - USER_UID=${GIT_USER_UID}
      - USER_GID=${GIT_USER_GID}

      # app.ini
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db

      - GITEA__server__DOMAIN="${GITEA_DOMAIN}"
      - GITEA__server__ROOT_URL="https://${GITEA_DOMAIN}/"
      - GITEA__server__HTTP_PORT=3000

      - GITEA__log__ROOT_PATH="/data/gitea/log"
    volumes:
      - ./services/gitea/data:/data
      - ./services/gitea/backup:/backup
      - /home/git/.ssh:/data/git/.ssh

  expenses:
    image: nginx:1.27-otel
    container_name: expenses
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ="Asia/Yekaterinburg"
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    volumes:
      # Папка expenses - это git репозиторий с расходами
      - ./services/expenses/data/expenses/results:/usr/share/nginx/html:ro

  dozzle:
    image: amir20/dozzle:v8.2.1
    container_name: dozzle
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ="Asia/Yekaterinburg"
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8

      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  wikijs:
    image: requarks/wiki:2.5
    container_name: wikijs
    restart: unless-stopped
    networks:
      - homelab
    environment:
      TZ: "Asia/Yekaterinburg"
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8

      DB_TYPE: postgres
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${PG_WIKIJS_USER}
      DB_PASS: ${PG_WIKIJS_PASSWORD}
      DB_NAME: ${PG_WIKIJS_DB}

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.23
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - PUID=${SERVER_UID}
      - PGID=${SERVER_GID}
    volumes:
      - ./services/calibre-web/data:/config

  photoprism:
    image: photoprism/photoprism:240711
    container_name: photoprism
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    # restart: unless-stopped
    stop_grace_period: 10s
    user: ${SERVER_UID}:${SERVER_GID}
    networks:
      - homelab
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # ports:
      # - "2342:2342"
    working_dir: "/photoprism"
    environment:
      TZ: "Asia/Yekaterinburg"
      # LANG: ru_RU.UTF-8
      # LANGUAGE: ru_RU.UTF-8
      # LC_ALL: ru_RU.UTF-8
      ###
      PHOTOPRISM_SITE_URL: "http://${PHOTOPRISM_DOMAIN}:2342/"
      ###
      PHOTOPRISM_ADMIN_USER: ${PHOTOPRISM_ADMIN_USER}
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      ###
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "${MARIADB_HOST}:${MARIADB_PORT}"
      PHOTOPRISM_DATABASE_NAME: ${MARIADB_PHOTOPRISM_DB}
      PHOTOPRISM_DATABASE_USER: ${MARIADB_PHOTOPRISM_USER}
      PHOTOPRISM_DATABASE_PASSWORD: ${MARIADB_PHOTOPRISM_PASSWORD}
      ###
      PHOTOPRISM_CONFIG_PATH: /photoprism/config
      PHOTOPRISM_DEFAULTS_YAML: /photoprism/config/defaults.yml
      PHOTOPRISM_BACKUP_PATH: /photoprism/backup
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - ./services/photoprism/data/config:/photoprism/config
      - ./services/photoprism/data/storage:/photoprism/storage
      - ./services/photoprism/data/import:/photoprism/import
      - ./services/photoprism/data/originals:/photoprism/originals
      - ./services/photoprism/backup:/photoprism/backup

...


