version: "3.4"

services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    # hostname: traefik.home.localhost
    restart: unless-stopped
    networks:
      - homelab
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Enables the web UI
      - "--api.insecure=true"

      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      # - "--entrypoints.ssh.address=:22"

      - "--log=true"
      # - "--log.level=DEBUG"
      - "--log.filePath=/var/log/traefik.log"
      - "--accessLog.filePath=/var/log/access_traefik.log"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/:/var/log/
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.home`)
      - traefik.http.routers.traefik.entrypoints=http
      # The Web UI (enabled by --api.insecure=true)
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  pihole:
    container_name: pihole
    image: pihole/pihole:2024.03.2
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ='Asia/Yekaterinburg'
      - VIRTUAL_HOST=pihole.home
      - FTLCONF_LOCAL_IPV4=${SERVER_IP}
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
    volumes:
      - ./services/pihole/config/etc-pihole:/etc/pihole
      - ./services/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.home`)
      - traefik.http.routers.pihole.entrypoints=http
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

