version: "3.4"

services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
      - REGRU_USERNAME=${REGRU_USERNAME}
      - REGRU_PASSWORD=${REGRU_PASSWORD}
    networks:
      - homelab
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/traefik/config/:/etc/traefik:ro
      - ./services/traefik/logs:/var/log/traefik
      - ./services/traefik/data/acme:/letsencrypt


  homer:
    image: b4bz/homer:v24.04.1
    container_name: homer
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
    networks:
      - homelab
    volumes:
      - ./services/homer/assets:/www/assets


  pihole:
    container_name: pihole
    image: pihole/pihole:2024.03.2
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ='Asia/Yekaterinburg'
      - VIRTUAL_HOST=pihole.home
      - FTLCONF_LOCAL_IPV4=${SERVER_IP}
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
    volumes:
      - ./services/pihole/config/etc-pihole:/etc/pihole
      - ./services/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d

  # gitea:
  #   image: gitea/gitea:1.21.11
  #   container_name: gitea
  #   restart: unless-stopped
  #   networks:
  #     - homelab
  #   environment:
  #     - TZ="Asia/Yekaterinburg"
  #     - LANG=ru_RU.UTF-8
  #     - LANGUAGE=ru_RU.UTF-8
  #     - LC_ALL=ru_RU.UTF-8
  #   # volumes:
  #     # - ./services/gitea/data:/data
  #     # - /home/git/.ssh:/data/git/.ssh
  #   # ports:
  #     # - "2222:22"
  #   # labels:
  #     # - traefik.enable=true
  #     # http
  #     # - traefik.http.routers.gitea-http.rule=Host(`gitea.home`)
  #     # - traefik.http.routers.gitea-http.entrypoints=http
  #     # - traefik.http.routers.gitea-http.service=gitea-http
  #     # - traefik.http.services.gitea-http.loadbalancer.server.port=3000
  #     # ssh
  #     # - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
  #     # - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
  #     # - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
  #     # - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22

