version: "3.4"

services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
    networks:
      - homelab
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true

      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.ssh.address=:22

      - --log=true
      - "--log.level=DEBUG"
      - --log.filePath=/var/log/traefik.log
      - --accessLog.filePath=/var/log/access_traefik.log
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/logs/:/var/log/
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.home`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  homer:
    image: b4bz/homer:v24.04.1
    container_name: homer
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
    networks:
      - homelab
    volumes:
      - ./services/homer/assets:/www/assets
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host(`homer.home`)
      - traefik.http.routers.homer.entrypoints=http
      - traefik.http.services.homer.loadbalancer.server.port=8080

  pihole:
    container_name: pihole
    image: pihole/pihole:2024.03.2
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ='Asia/Yekaterinburg'
      - VIRTUAL_HOST=pihole.home
      - FTLCONF_LOCAL_IPV4=${SERVER_IP}
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
    volumes:
      - ./services/pihole/config/etc-pihole:/etc/pihole
      - ./services/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.home`)
      - traefik.http.routers.pihole.entrypoints=http
      - traefik.http.services.pihole.loadbalancer.server.port=80

  gitea:
    image: gitea/gitea:1.21.11
    container_name: gitea
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ="Asia/Yekaterinburg"
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    # volumes:
      # - ./services/gitea/data:/data
      # - /home/git/.ssh:/data/git/.ssh
    # ports:
      # - "2222:22"
    labels:
      - traefik.enable=true
      # http
      - traefik.http.routers.gitea-http.rule=Host(`gitea.home`)
      - traefik.http.routers.gitea-http.entrypoints=http
      # - traefik.http.routers.gitea-http.service=gitea-http
      - traefik.http.services.gitea-http.loadbalancer.server.port=3000
      # ssh
      # - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      # - traefik.tcp.routers.gitea-ssh.entrypoints=ssh
      # - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
      # - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22



