version: "3.4"

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:2024.03.2
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8088:80/tcp"
    environment:
      TZ: 'Asia/Yekaterinburg'
      # WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
      FTLCONF_LOCAL_IPV4: 192.168.5.55
      WEBPASSWORD: 123
    volumes:
      - ./services/pihole/config/etc-pihole:/etc/pihole
      - ./services/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d

