---
version: "3.4"

services:

  glances:
    image: nicolargo/glances:dev
    container_name: glances
    restart: unless-stopped
    network_mode: "host"
    pid: host
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/glances/glances.conf:/glances/conf/glances.conf"
      - /:/rootfs:ro
    environment:
      - TZ="Asia/Yekaterinburg"
      - "GLANCES_OPT=-C /glances/conf/glances.conf -w"


  gitea:
    image: gitea/gitea:1.21.11
    container_name: gitea
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ="Asia/Yekaterinburg"
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8

      # Нужно для разрешения записи в /home/git/.ssh
      - USER_UID=${GIT_USER_UID}
      - USER_GID=${GIT_USER_GID}

      # app.ini
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db

      - GITEA__server__DOMAIN="${GITEA_DOMAIN}"
      - GITEA__server__ROOT_URL="https://${GITEA_DOMAIN}/"
      - GITEA__server__HTTP_PORT=3000

      - GITEA__log__ROOT_PATH="/data/gitea/log"
    volumes:
      - ./services/gitea/data:/data
      - /home/git/.ssh:/data/git/.ssh

...

