version: "3.4"

services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
      - REGRU_USERNAME=${REGRU_USERNAME}
      - REGRU_PASSWORD=${REGRU_PASSWORD}
    networks:
      - homelab
    ports:
      - 80:80
      - 443:443
      - 2222:2222
    volumes:
      - ./services/traefik/config/:/etc/traefik:ro
      - ./services/traefik/logs:/var/log/traefik
      - ./services/traefik/data/acme:/letsencrypt


  homer:
    image: b4bz/homer:v24.04.1
    container_name: homer
    restart: unless-stopped
    environment:
      - TZ="Asia/Yekaterinburg"
    networks:
      - homelab
    volumes:
      - ./services/homer/assets:/www/assets


  pihole:
    image: pihole/pihole:2024.03.2
    container_name: pihole
    restart: unless-stopped
    networks:
      - homelab
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ='Asia/Yekaterinburg'
      - VIRTUAL_HOST=pihole.feelinglight.homes
      - FTLCONF_LOCAL_IPV4=${SERVER_IP}
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD}
    volumes:
      - ./services/pihole/config/etc-pihole:/etc/pihole
      - ./services/pihole/config/etc-dnsmasq.d:/etc/dnsmasq.d
      - ./services/pihole/backup:/backup

  gitea:
    image: gitea/gitea:1.21.11
    container_name: gitea
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - TZ="Asia/Yekaterinburg"
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8

      # Нужно для разрешения записи в /home/git/.ssh
      - USER_UID=${GIT_USER_UID}
      - USER_GID=${GIT_USER_GID}

      # app.ini
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db

      - GITEA__server__DOMAIN="${GITEA_DOMAIN}"
      - GITEA__server__ROOT_URL="https://${GITEA_DOMAIN}/"
      - GITEA__server__HTTP_PORT=3000

      - GITEA__log__ROOT_PATH="/data/gitea/log"
    volumes:
      - ./services/gitea/data:/data
      - /home/git/.ssh:/data/git/.ssh

