- name: Create git user
  become: true
  ansible.builtin.user:
    uid: "{{ git_user_uid }}"
    name: git
    password: '!'

- name: Make ssh folder for git user
  become: true
  file:
    path: "{{ git_user_ssh_folder }}"
    state: directory
    owner: git
    group: git

- name: Generate ssh keys for git user
  become: true
  openssh_keypair:
    path: "{{ git_user_ssh_folder }}/id_rsa"
    owner: git
    group: git

- name: Get git user pub key
  become: true
  ansible.builtin.slurp:
    src: /home/git/.ssh/id_rsa.pub
  register: git_pub_key

- name: Add pub key to authorized_key
  become: true
  ansible.posix.authorized_key:
    user: git
    state: present
    key: "{{ git_pub_key['content'] | b64decode}}"

