- name: Copy ssh redirect script
  become: true
  copy:
    src: gitea_ssh.sh
    dest: "{{ gitea_ssh_redirect_bin }}"
    mode: a+x

- name: Setup gitea ssh authorization
  become: true
  template:
    src: git_user_ssh
    dest: /etc/ssh/sshd_config.d/git_user_ssh

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted