- name: Install packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - git
      - docker.io
      - docker
      - docker-compose

- name: Make git user
  import_tasks: git_user.yml

- name: Setup Gitea
  import_tasks: setup_gitea.yml

- name: Redirect ssh for gitea
  import_tasks: gitea_redirect_ssh.yml

- name: Setup Nginx
  import_tasks: setup_nginx.yml
