---

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  # level: DEBUG
  level: INFO

accessLog:
  filePath: /var/log/traefik/access_traefik.log
  # fields:
    # headers:
      # defaultMode: keep


api:
  dashboard: true
  # debug: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: :443

  ssh:
    address: :2222


certificatesResolvers:
  letsencrypt_regru:
    acme:
      # Тестовый сервер letsencrypt
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: kolpacc123@mail.ru
      storage: /letsencrypt/acme.json
      # Период обновления сертификатов, в часах
      # certificatesDuration: 2
      dnsChallenge:
        provider: regru
        propagation:
          # Задержка проверки DNS challenge после добавления TXT записи в reg.ru, в секундах
          delayBeforeChecks: 900


providers:
  file:
    directory: /etc/traefik/services
    watch: true

...

