global:
  checkNewVersion: false
  sendAnonymousUsage: false


log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access_traefik.log


api:
  dashboard: true
  # debug: true


entryPoints:
  web:
    address: :80
#     http:
#       redirections:
#         entryPoint:
#           to: https
#           scheme: https
#           permanent: true
  web-secure:
    address: :443
  ssh:
    address: :22


providers:
  file:
    directory: /etc/traefik/services
    watch: true


