http:
  routers:
    authelia:
      service: authelia
      rule: Host(`{{ env "AUTHELIA_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  services:
    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091

