http:
  routers:
    authelia:
      service: authelia
      rule: Host(`{{ env "AUTHELIA_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  middlewares:
    authelia:
      forwardAuth:
        address: 'http://authelia:9091/api/authz/forward-auth'
        trustForwardHeader: true
        authResponseHeaders:
          - 'Remote-User'
          - 'Remote-Groups'
          - 'Remote-Email'
          - 'Remote-Name'

  services:
    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091

