http:
  routers:
    bareos:
      service: bareos
      rule: Host(`bareos.feelinglight.homes`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  services:
    bareos:
      loadBalancer:
        servers:
          - url: http://bareos-webui:9100

