http:
  routers:
    bareos:
      service: bareos
      rule: Host(`{{ env "BAREOS_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      middlewares:
        - authelia@file
      tls:
        certResolver: letsencrypt_regru

  services:
    bareos:
      loadBalancer:
        servers:
          - url: http://bareos-webui:9100

