http:
  routers:
    gitea-web:
      service: gitea-web
      rule: Host(`gitea.{{ env "SERVICES_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  services:
    gitea-web:
      loadBalancer:
        servers:
          - url: http://gitea:3000

tcp:
  routers:
    gitea-ssh:
      service: gitea-ssh
      rule: HostSNI(`*`)
      entryPoints:
        - ssh

  services:
    gitea-ssh:
      loadBalancer:
        servers:
        - address: gitea:22

