---

http:
  routers:
    glances:
      service: glances
      rule: Host(`{{ env "GLANCES_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  services:
    glances:
      loadBalancer:
        servers:
          - url: http://glances.feelinglight.homes:61208

...

