---

http:
  routers:
    glances:
      service: glances
      rule: Host(`{{ env "GLANCES_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      middlewares:
        - authelia@file
      tls:
        certResolver: letsencrypt_regru

  services:
    glances:
      loadBalancer:
        servers:
          # glances работает в режиме network_mode: host
          - url: http://{{ env "GLANCES_DOMAIN" }}:61208

...

