http:
  routers:
    homer:
      service: homer
      rule: Host(`{{ env "HOMER_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  services:
    homer:
      loadBalancer:
        servers:
          - url: http://homer:8080

