---

http:
  routers:
    metabase:
      service: metabase
      rule: Host(`{{ env "METABASE_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      middlewares:
        - authelia@file
      tls:
        certResolver: letsencrypt_regru

  services:
    metabase:
      loadBalancer:
        servers:
          - url: http://metabase:3000

...

