---

http:
  middlewares:
    authelia:
      forwardAuth:
        address: 'https://authelia.feelinglight.homes/api/authz/forward-auth'
        trustForwardHeader: true
        authResponseHeaders:
          - 'Remote-User'
          - 'Remote-Groups'
          - 'Remote-Email'
          - 'Remote-Name'

...

