http:
  routers:
    pihole:
      service: pihole
      rule: Host(`{{ env "PIHOLE_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      middlewares:
        - authelia@file
      tls:
        certResolver: letsencrypt_regru

  services:
    pihole:
      loadBalancer:
        servers:
          - url: http://pihole:80

