http:
  routers:
    pihole:
      service: pihole
      rule: Host(`pihole.feelinglight.homes`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru

  services:
    pihole:
      loadBalancer:
        servers:
          - url: http://pihole:80

