http:
  routers:
    traefik:
      service: api@internal
      rule: Host(`traefik.feelinglight.homes`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru


