http:
  routers:
    traefik:
      service: api@internal
      rule: Host(`traefik.{{ env "SERVICES_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru


