http:
  routers:
    traefik:
      service: api@internal
      rule: Host(`{{ env "TRAEFIK_DOMAIN" }}`)
      entryPoints:
        # - web
        - web-secure
      tls:
        certResolver: letsencrypt_regru


