---

server:
  address: 'tcp://:9091'

log:
  level: 'debug'

identity_validation:
  reset_password:
    jwt_secret: '{{ secret "/run/secrets/JWT_SECRET" }}'

authentication_backend:
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'deny'
  rules:
    - domain: '{{ mustEnv "BAREOS_DOMAIN" }}'
      policy: 'bypass'
    - domain: '{{ mustEnv "GITEA_DOMAIN" }}'
      policy: 'bypass'
    - domain: '{{ mustEnv "GLANCES_DOMAIN" }}'
      policy: 'one_factor'
      subject:
        - ['group:admins']
    - domain: '{{ mustEnv "HOMER_DOMAIN" }}'
      policy: 'one_factor'
    - domain: '{{ mustEnv "PIHOLE_DOMAIN" }}'
      policy: 'one_factor'
      subject:
        - ['group:admins']
    - domain: '{{ mustEnv "TRAEFIK_DOMAIN" }}'
      policy: 'one_factor'
      subject:
        - ['group:admins']
    - domain: '{{ mustEnv "EXPENSES_DOMAIN" }}'
      policy: 'one_factor'
    - domain: '{{ mustEnv "DOZZLE_DOMAIN" }}'
      policy: 'one_factor'
      subject:
        - ['group:admins']
    - domain: '{{ mustEnv "WIKIJS_DOMAIN" }}'
      policy: 'bypass'
    - domain: '{{ mustEnv "CALIBRE_DOMAIN" }}'
      policy: 'bypass'
    - domain: '{{ mustEnv "PHOTOPRISM_DOMAIN" }}'
      policy: 'bypass'
    - domain: '{{ mustEnv "SCRUTINY_DOMAIN" }}'
      policy: 'one_factor'
      subject:
        - ['group:admins']

session:
  # secret: 'insecure_session_secret'

  cookies:
    - name: 'authelia_session'
      domain: '{{ mustEnv "SERVICES_DOMAIN" }}'
      authelia_url: 'https://{{ mustEnv "AUTHELIA_DOMAIN" }}'
      expiration: '1 hour'
      inactivity: '5 minutes'

regulation:
  max_retries: 10
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: '{{ secret "/run/secrets/STORAGE_ENCRYPTION_KEY" }}'
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: '/config/notification.txt'

...

