---

users:
  authelia:
    disabled: false
    displayname: "authelia"
    # Команда для генерации пароля:
    # docker exec -it authelia authelia crypto hash generate --config /config/configuration.yaml
    # Пароль - authelia
    password: "$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/"
    email: authelia@authelia.com
    groups:
      - admins

...

