---


git_user_uid: 2000
git_user_ssh_folder: "/home/git/.ssh"

gitea_dir: "{{ server_data_dir }}/gitea"

gitea_conf_dir: "{{ gitea_dir }}/data/gitea/conf"
gitea_conf_file: "{{ gitea_conf_dir }}/app.ini"

gitea_data_dir: "{{ gitea_dir }}/data"

gitea_ssh_redirect_bin: "/usr/local/bin/gitea"



