- name: Install packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - git
      - docker.io
      - docker
      - docker-compose
      - openssh-server

- name: Setup Gitea
  import_tasks: setup_gitea.yml

- name: Setups ssh redirect for gitea
  import_tasks: setup_ssh.yml

# - name: Setup Nginx
#   import_tasks: setup_nginx.yml
