- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - git
      - fcgiwrap
      - apache2-utils
      - python3-passlib
    # update_cache: true

- name: Make repositories folder
  become: true
  file:
    path: "{{ repos_dir }}"
    owner: www-data
    group: www-data
    state: directory

- name: Make Nginx config ({{ git_srv_domain }})
  become: true
  template:
    src: nginx_git.j2
    dest: "/etc/nginx/sites-available/{{ git_srv_domain }}"

- name: Create git user
  become: true
  community.general.htpasswd:
    path: /etc/nginx/.gitpasswd
    name: git
    password: 123
    owner: root
    group: www-data


- name: Restart Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
