- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    update_cache: true

- name: Restart Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
