- name: Make sites folder
  become: true
  file:
    path: "{{ sites_dir }}"
    state: directory

# rsync с sudo по другому не работает
- name: Allow sudo nopasswd
  become: true
  copy:
    src: files/rsync_sudo
    dest: /etc/sudoers.d/rsync_sudo

- name: Copy site ({{ site_info.name }})
  synchronize:
    src: "{{ site_info.path }}/"
    dest: "{{ sites_dir }}/{{ site_info.domain }}/"
    rsync_path: "sudo rsync"

- name: Make Nginx config ({{ site_info.name }})
  become: true
  template:
    src: nginx_site.j2
    dest: "/etc/nginx/sites-available/{{ site_info.domain }}"

- name: Enable site ({{ site_info.name }})
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ site_info.domain }}"
    dest: "/etc/nginx/sites-enabled/{{ site_info.domain }}"
    state: link

- name: Restart Nginx
  become: true
  service:
    name: nginx
    state: restarted
