---
title: "Home Lab"
subtitle: "FeelingLight"
logo: "assets/icons/homelab.jpg"

header: false
footer: '' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/images/3.png" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.5)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/images/1.png"

services:

  - name: "💾 Storage"
    items:
      - name: "Bareos"
        logo: "assets/icons/bareos.png"
        subtitle: "Backups"
        url: "https://bareos.feelinglight.homes"

  - name: "💻 Home Lab"
    items:
      - name: "Traefik"
        logo: "assets/icons/traefik.png"
        subtitle: "Reverse Proxy"
        url: "https://traefik.feelinglight.homes"

      - name: "PiHole"
        logo: "assets/icons/pihole.svg"
        subtitle: "DNS Server"
        url: "https://pihole.feelinglight.homes"

      - name: "Gitea"
        logo: "assets/icons/gitea.svg"
        subtitle: "Git remote server"
        url: "https://gitea.feelinglight.homes"

      - name: "Glances"
        logo: "assets/icons/glances.svg"
        subtitle: "Server monitoring"
        url: "https://glances.feelinglight.homes"

