---
title: "Home Lab"
subtitle: "FeelingLight"
logo: "assets/icons/homelab.jpg"

header: false
footer: '' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
connectivityCheck: false

theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/images/3.png" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.5)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/images/1.png"

services:

  - name: "Access"
    items:
      - name: "Traefik"
        logo: "assets/icons/traefik.png"
        subtitle: "Обратный прокси сервер"
        url: "https://traefik.feelinglight.homes"

      - name: "PiHole"
        logo: "assets/icons/pihole.svg"
        subtitle: "DNS сервер"
        url: "https://pihole.feelinglight.homes"

      - name: "Authelia"
        logo: "assets/icons/authelia.svg"
        subtitle: "Сервер авторизации"
        url: "https://pihole.feelinglight.homes"

  - name: "Monitoring"
    items:
      - name: "Glances"
        logo: "assets/icons/glances.png"
        subtitle: "Панель мониторинга linux сервера"
        url: "https://glances.feelinglight.homes"

      - name: "Dozzle"
        logo: "assets/icons/dozzle.svg"
        subtitle: "Логи контейнеров"
        url: "https://dozzle.feelinglight.homes"

      - name: "Scrutiny"
        logo: "assets/icons/scrutiny.png"
        subtitle: "S.M.A.R.T"
        url: "https://scrutiny.feelinglight.homes"

  - name: "Applications"
    items:
      - name: "Photoprism"
        logo: "assets/icons/photoprism.svg"
        subtitle: "Хранилище фотографий"
        url: "https://photoprism.feelinglight.homes"

      - name: "Nextcloud"
        logo: "assets/icons/nextcloud.svg"
        subtitle: "Файловое хранилище"
        url: "https://nextcloud.feelinglight.homes"

      - name: "Gitea"
        logo: "assets/icons/gitea.svg"
        subtitle: "Удаленный git сервер"
        url: "https://gitea.feelinglight.homes"

      - name: "Расходы"
        logo: "assets/icons/expenses.png"
        subtitle: "Графики расходов"
        url: "https://expenses.feelinglight.homes"

      - name: "WikiJs"
        logo: "assets/icons/wikijs-butterfly.svg"
        subtitle: "База знаний"
        url: "https://wikijs.feelinglight.homes"

      - name: "Calibre"
        logo: "assets/icons/calibre.png"
        subtitle: "Электронная библиотека"
        url: "https://calibre.feelinglight.homes"

      - name: "Bareos"
        logo: "assets/icons/bareos.png"
        subtitle: "Резервное копирование"
        url: "https://bareos.feelinglight.homes"

