version: '3'
services:
  bareos-dir:
    container_name: bareos-dir
    image: bar-dir
    volumes:
      - ./etc/dir:/etc/bareos
      # - <BAREOS_DATA_PATH>:/var/lib/bareos #required for MyCatalog backup
    environment:
      - DB_INIT=true
      - DB_UPDATE=false
      - DB_HOST=bareos-db
      - DB_PORT=5432
      - DB_NAME=bareos
      - DB_USER=bareos
      - DB_PASSWORD=admin
      - DB_ADMIN_USER=admin
      - DB_ADMIN_PASSWORD=admin
      - BAREOS_FD_HOST=bareos-fd
      - BAREOS_FD_PASSWORD=admin
      - BAREOS_SD_HOST=bareos-sd
      - BAREOS_SD_PASSWORD=admin
      - BAREOS_WEBUI_PASSWORD=admin
      - SMTP_HOST=smtpd
      - SENDER_MAIL=your-sender@mail.address #optional
      - ADMIN_MAIL=your@mail.address # Change me!
      # Optional you can get backup notification via Slack or Telegram
      # - WEBHOOK_NOTIFICATION=true # true or false if set to true email notification gets disabled
      # - WEBHOOK_TYPE=slack # choose slack or telegram
      # - WEBHOOK_URL= # set the slack or telegram URL
      # - WEBHOOK_CHAT_ID= # for telegram only set the <chat_id>
    depends_on:
      - postgres-db

  bareos-sd:
    container_name: bareos-sd
    image: bar-sd
    ports:
      - 9103:9103
    volumes:
      - ./etc/sd:/etc/bareos
      # - <BAREOS_BKP_VOLUME_PATH>:/var/lib/bareos/storage
    environment:
      - BAREOS_SD_PASSWORD=admin

  bareos-fd:
    container_name: bareos-fd
    image: bar-fd
    volumes:
      - ./etc/fd:/etc/bareos
      # - <BAREOS_CONF_PATH>:/etc/bareos
      # - <BAREOS_DATA_PATH>:/var/lib/bareos-director #required for MyCatalog backup
    environment:
      - BAREOS_FD_PASSWORD=admin
      - FORCE_ROOT=false

  bareos-webui:
    container_name: bareos-webui
    image: bar-web
    ports:
      - 8080:80
    environment:
      - BAREOS_DIR_HOST=bareos-dir
      - SERVER_STATS=yes #optional enable apache server statistics
    volumes:
      - ./etc/web:/etc/bareos
      # - <BAREOS_CONF_PATH>:/etc/bareos-webui

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    # volumes:
      # - <DB_DATA_PATH>:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_INITDB_ARGS=--encoding=SQL_ASCII

  # smtpd:
  #   container_name: smtpd
  #   image: namshi/smtp
