version: '3'
services:
  bareos-dir:
    container_name: bareos-dir
    image: bar-dir
    command: /bin/bash
    volumes:
      - ./etc_probe/dir:/etc_bareos:ro
      # - <BAREOS_DATA_PATH>:/var/lib/bareos #required for MyCatalog backup
    # environment:
      # - DB_INIT=true
      # - DB_UPDATE=false
    depends_on:
      - postgres-db

  bareos-sd:
    container_name: bareos-sd
    image: bar-sd
    ports:
      - 9103:9103
    volumes:
      - ./etc/sd:/etc/bareos
      # - <BAREOS_BKP_VOLUME_PATH>:/var/lib/bareos/storage
    environment:
      - BAREOS_SD_PASSWORD=admin

  bareos-fd:
    container_name: bareos-fd
    image: bar-fd
    volumes:
      - ./etc/fd:/etc/bareos
      # - <BAREOS_CONF_PATH>:/etc/bareos
      # - <BAREOS_DATA_PATH>:/var/lib/bareos-director #required for MyCatalog backup
    environment:
      - BAREOS_FD_PASSWORD=admin
      - FORCE_ROOT=false

  bareos-webui:
    container_name: bareos-webui
    image: bar-web
    ports:
      - 8080:80
    environment:
      - BAREOS_DIR_HOST=bareos-dir
      - SERVER_STATS=yes #optional enable apache server statistics
    volumes:
      - ./etc/web:/etc/bareos
      # - <BAREOS_CONF_PATH>:/etc/bareos-webui

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    # volumes:
      # - <DB_DATA_PATH>:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_INITDB_ARGS=--encoding=SQL_ASCII

  # smtpd:
  #   container_name: smtpd
  #   image: namshi/smtp
