version: '3'
services:

  bareos-dir:
    container_name: bareos-dir
    image: bar-dir
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - DB_INIT=true
      ###
      - BAREOS__DB_HOST=${POSTGRES_HOST}
      - BAREOS__DB_PORT=${POSTGRES_PORT}
      - BAREOS__DB_NAME=bareos
      - BAREOS__DB_USER=bareos
      - BAREOS__DB_PASSWORD=${BAREOS__DB_PASSWORD}
      ###
      - POSTGRES_ADMIN_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      ###
      - BAREOS__DIRECTOR_PASSWORD=${BAREOS__DIRECTOR_PASSWORD}
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}
      - BAREOS__WEBUI_CONSOLE_PASSWORD=${BAREOS__WEBUI_CONSOLE_PASSWORD}
      ###
      - BAREOS__SD_ADDRESS=bareos-sd
      - BAREOS__SD_PASSWORD=${BAREOS__SD_PASSWORD}
      ###
      - BAREOS__FD_DOCKER_ADDRESS=${BAREOS__FD_DOCKER_ADDRESS}
      - BAREOS__FD_DOCKER_PASSWORD=${BAREOS__FD_DOCKER_PASSWORD}

      - BAREOS__FD_DMITRY_ADDRESS=${BAREOS__FD_DMITRY_ADDRESS}
      - BAREOS__FD_DMITRY_PASSWORD=${BAREOS__FD_DMITRY_PASSWORD}
      ###
    volumes:
      - ./bareos_tmp/backups/bootstraps:/backups/bootstraps
      - ./services/bareos/config/etc_bareos/dir:/etc_bareos:ro
      # - ./services/bareos/config/scripts/remove_expired_volumes.py:/usr/local/bin/remove_expired_volumes.py
      - ./services/bareos/config/scripts:/usr/local/bin/
    depends_on:
      postgres-db:
        condition: service_healthy

  bareos-sd:
    container_name: bareos-sd
    image: bar-sd
    ports:
      - 9103:9103
    volumes:
      - ./bareos_tmp/backups:/backups
      - ./services/bareos/config/etc_bareos/sd:/etc_bareos:ro
    environment:
      - TZ=Asia/Yekaterinburg
      - BAREOS__SD_PASSWORD=${BAREOS__SD_PASSWORD}
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}

  bareos-fd:
    container_name: bareos-fd
    image: bar-fd
    volumes:
      - ./bareos_tmp/test_data:/test_data
      - ./services/bareos/config/etc_bareos/fd:/etc_bareos:ro
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}
      - BAREOS__FD_DOCKER_PASSWORD=${BAREOS__FD_DOCKER_PASSWORD}

  bareos-webui:
    container_name: bareos-webui
    image: bar-web
    ports:
      - 9100:9100
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - BAREOS__DIRECTOR_HOST=bareos-dir
    volumes:
      - ./services/bareos/config/etc_nginx/default:/etc/nginx/sites-enabled/default
      - ./services/bareos/config/etc_bareos/webui:/etc_bareos:ro

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    environment:
      - TZ=Asia/Yekaterinburg
      ###
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s

  # smtpd:
  #   container_name: smtpd
  #   image: namshi/smtp

