version: '3'
services:

  bareos-dir:
    container_name: bareos-dir
    image: bar-dir
    environment:
      - DB_INIT=true
      ###
      - BAREOS__DB_HOST=${POSTGRES_HOST}
      - BAREOS__DB_PORT=${POSTGRES_PORT}
      - BAREOS__DB_NAME=bareos
      - BAREOS__DB_USER=bareos
      - BAREOS__DB_PASSWORD=${BAREOS__DB_PASSWORD}
      ###
      - POSTGRES_ADMIN_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
      ###
      - BAREOS__DIRECTOR_PASSWORD=${BAREOS__DIRECTOR_PASSWORD}
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}
      - BAREOS__WEBUI_CONSOLE_PASSWORD=${BAREOS__WEBUI_CONSOLE_PASSWORD}
      ###
      - BAREOS__SD_ADDRESS=bareos-sd
      - BAREOS__SD_PASSWORD=${BAREOS__SD_PASSWORD}
      ###
      - BAREOS__FD_DOCKER_ADDRESS=${BAREOS__FD_DOCKER_ADDRESS}
      - BAREOS__FD_DOCKER_PASSWORD=${BAREOS__FD_DOCKER_PASSWORD}

      - BAREOS__FD_DMITRY_ADDRESS=${BAREOS__FD_DMITRY_ADDRESS}
      - BAREOS__FD_DMITRY_PASSWORD=${BAREOS__FD_DMITRY_PASSWORD}
      ###
    volumes:
      - ./services/bareos/config/etc_probe/dir:/etc_bareos:ro
    depends_on:
      postgres-db:
        condition: service_healthy

  bareos-sd:
    container_name: bareos-sd
    image: bar-sd
    ports:
      - 9103:9103
    volumes:
      - ./services/bareos/config/etc_probe/sd:/etc_bareos:ro
    environment:
      - BAREOS__SD_PASSWORD=${BAREOS__SD_PASSWORD}
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}

  bareos-fd:
    container_name: bareos-fd
    image: bar-fd
    volumes:
      - ./services/bareos/config/etc_probe/fd:/etc_bareos:ro
    environment:
      # - BAREOS__FD_DOCKER_NAME=${BAREOS__FD_DOCKER_NAME}
      - BAREOS__MONITOR_CONSOLE_PASSWORD=${BAREOS__MONITOR_CONSOLE_PASSWORD}
      - BAREOS__FD_DOCKER_PASSWORD=${BAREOS__FD_DOCKER_PASSWORD}

  bareos-webui:
    container_name: bareos-webui
    image: bar-web
    ports:
      - 9100:9100
    environment:
      - BAREOS__DIRECTOR_HOST=bareos-dir
    volumes:
      - ./services/bareos/config/nginx/default:/etc/nginx/sites-enabled/default
      - ./services/bareos/config/etc_probe/webui:/etc_bareos:ro

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s

  # smtpd:
  #   container_name: smtpd
  #   image: namshi/smtp
